/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_anglade_version_console;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author marin
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    GrilleDeJeu grille;
    int nbCoups;
    int dimension;
    int nbCoupsMax;
    int nbMelange;
    int i;

    public FenetrePrincipale() {
        initComponents();
        BoutonFacile.setVisible(false);
        BoutonMoyen.setVisible(false);
        BoutonDifficile.setVisible(false);
        PanneauGrille.setVisible(false);

    }

    public void creerPanel() {
        // initComponents();
        int nbLignes = dimension;
        int nbColonnes = dimension;
        this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
        PanneauGrille.setLayout(new GridLayout(dimension, dimension));
        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j], 36, 36); // création d'un bouton

                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
        }
        boutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        getContentPane().add(boutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1 * 40, nbLignes * 40));
        this.pack();
        this.revalidate();
        // création du panneau de boutons verticaux (pour les lignes)
        for (i = 0; i < nbLignes; i++) {
            JButton bouton_ligne = new JButton();
            ActionListener ecouteurClick = new ActionListener() {
                final int j = i;

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerLigneDeCellules(j);
                    repaint();
                }
            };
            bouton_ligne.addActionListener(ecouteurClick);
            boutonsVerticaux.add(bouton_ligne);
        };
        boutonsHorizontaux.setLayout(new GridLayout(nbColonnes, 1));
        getContentPane().add(boutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1 * 40, nbColonnes * 40));
        this.pack();
        this.revalidate();
        // création du panneau de boutons verticaux (pour les lignes)
        for (i = 0; i < nbLignes; i++) {
            JButton bouton_ligne = new JButton();
            ActionListener ecouteurClick = new ActionListener() {
                final int j = i;

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerLigneDeCellules(j);
                    repaint();
                }
            };
            bouton_ligne.addActionListener(ecouteurClick);
            boutonsHorizontaux.add(bouton_ligne);
        };
        PanneauGrille.setVisible(true);

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, nbColonnes * 40, nbLignes * 40));
        this.pack();
        this.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        boutonsVerticaux = new javax.swing.JPanel();
        demanderNiveau = new javax.swing.JButton();
        BoutonFacile = new javax.swing.JButton();
        BoutonMoyen = new javax.swing.JButton();
        BoutonDifficile = new javax.swing.JButton();
        boutonsHorizontaux = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(102, 102, 255));
        PanneauGrille.setAutoscrolls(true);

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 360, 360));

        javax.swing.GroupLayout boutonsVerticauxLayout = new javax.swing.GroupLayout(boutonsVerticaux);
        boutonsVerticaux.setLayout(boutonsVerticauxLayout);
        boutonsVerticauxLayout.setHorizontalGroup(
            boutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        boutonsVerticauxLayout.setVerticalGroup(
            boutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(boutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, 360));

        demanderNiveau.setText("Choix du niveau");
        demanderNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demanderNiveauActionPerformed(evt);
            }
        });
        getContentPane().add(demanderNiveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        BoutonFacile.setText("Facile");
        BoutonFacile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonFacileActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonFacile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        BoutonMoyen.setText("Moyen");
        BoutonMoyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMoyenActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonMoyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        BoutonDifficile.setText("Difficile");
        BoutonDifficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonDifficileActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonDifficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        boutonsHorizontaux.setPreferredSize(new java.awt.Dimension(360, 0));

        javax.swing.GroupLayout boutonsHorizontauxLayout = new javax.swing.GroupLayout(boutonsHorizontaux);
        boutonsHorizontaux.setLayout(boutonsHorizontauxLayout);
        boutonsHorizontauxLayout.setHorizontalGroup(
            boutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        boutonsHorizontauxLayout.setVerticalGroup(
            boutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(boutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 360, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demanderNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demanderNiveauActionPerformed
        // TODO add your handling code here:
        BoutonMoyen.setVisible(true);
        BoutonDifficile.setVisible(true);
        BoutonFacile.setVisible(true);

    }//GEN-LAST:event_demanderNiveauActionPerformed

    private void BoutonMoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMoyenActionPerformed
        // TODO add your handling code here:
        this.dimension = 7;
        creerPanel();
    }//GEN-LAST:event_BoutonMoyenActionPerformed

    private void BoutonFacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonFacileActionPerformed
        // TODO add your handling code here:
        this.dimension = 5;
        creerPanel();
    }//GEN-LAST:event_BoutonFacileActionPerformed

    private void BoutonDifficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonDifficileActionPerformed
        // TODO add your handling code here:
        this.dimension = 10;
        creerPanel();


    }//GEN-LAST:event_BoutonDifficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonDifficile;
    private javax.swing.JButton BoutonFacile;
    private javax.swing.JButton BoutonMoyen;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel boutonsHorizontaux;
    private javax.swing.JPanel boutonsVerticaux;
    private javax.swing.JButton demanderNiveau;
    // End of variables declaration//GEN-END:variables
}
